/**
 * SAE J1939-71 suspect parameter names and J1939-73 failure mode identifiers.
 *
 * The FMI list is complete and normative. The SPN list covers the parameters
 * a heavy-duty engine commonly reports faults against; anything not listed is
 * displayed by number, which is what the ECM actually reported.
 */

export const FMI_NAMES: Record<number, string> = {
  0: 'Data valid but above normal operational range - most severe level',
  1: 'Data valid but below normal operational range - most severe level',
  2: 'Data erratic, intermittent or incorrect',
  3: 'Voltage above normal or shorted to high source',
  4: 'Voltage below normal or shorted to low source',
  5: 'Current below normal or open circuit',
  6: 'Current above normal or grounded circuit',
  7: 'Mechanical system not responding or out of adjustment',
  8: 'Abnormal frequency, pulse width or period',
  9: 'Abnormal update rate',
  10: 'Abnormal rate of change',
  11: 'Root cause not known',
  12: 'Bad intelligent device or component',
  13: 'Out of calibration',
  14: 'Special instructions',
  15: 'Data valid but above normal operating range - least severe level',
  16: 'Data valid but above normal operating range - moderately severe level',
  17: 'Data valid but below normal operating range - least severe level',
  18: 'Data valid but below normal operating range - moderately severe level',
  19: 'Received network data in error',
  20: 'Data drifted high',
  21: 'Data drifted low',
  31: 'Condition exists',
}

/** Short FMI label for narrow table columns. */
export const FMI_SHORT: Record<number, string> = {
  0: 'Above normal - most severe',
  1: 'Below normal - most severe',
  2: 'Data erratic',
  3: 'Voltage above normal',
  4: 'Voltage below normal',
  5: 'Current below normal / open circuit',
  6: 'Current above normal / grounded',
  7: 'Mechanical system not responding',
  8: 'Abnormal frequency',
  9: 'Abnormal update rate',
  10: 'Abnormal rate of change',
  11: 'Root cause not known',
  12: 'Bad device or component',
  13: 'Out of calibration',
  14: 'Special instructions',
  15: 'Above normal - least severe',
  16: 'Above normal - moderate',
  17: 'Below normal - least severe',
  18: 'Below normal - moderate',
  19: 'Network data in error',
  20: 'Data drifted high',
  21: 'Data drifted low',
  31: 'Condition exists',
}

export function fmiName(fmi: number): string {
  return FMI_NAMES[fmi] ?? `Unknown failure mode ${fmi}`
}

export function fmiShort(fmi: number): string {
  return FMI_SHORT[fmi] ?? `FMI ${fmi}`
}

export const SPN_NAMES: Record<number, string> = {
  27: 'EGR Valve Position',
  51: 'Engine Throttle Position',
  70: 'Parking Brake Switch',
  84: 'Wheel-Based Vehicle Speed',
  91: 'Accelerator Pedal Position 1',
  94: 'Engine Fuel Delivery Pressure',
  97: 'Water In Fuel Indicator',
  98: 'Engine Oil Level',
  100: 'Engine Oil Pressure',
  102: 'Engine Intake Manifold #1 Pressure',
  103: 'Turbocharger 1 Speed',
  105: 'Engine Intake Manifold #1 Temperature',
  107: 'Engine Air Filter 1 Differential Pressure',
  108: 'Barometric Pressure',
  110: 'Engine Coolant Temperature',
  111: 'Engine Coolant Level',
  132: 'Engine Air Inlet Flow Rate',
  157: 'Engine Injector Metering Rail 1 Pressure',
  158: 'Keyswitch Battery Potential',
  164: 'Engine Injection Control Pressure',
  168: 'Battery Potential / Power Input 1',
  171: 'Ambient Air Temperature',
  172: 'Engine Air Inlet Temperature',
  174: 'Engine Fuel Temperature',
  175: 'Engine Oil Temperature 1',
  177: 'Transmission Oil Temperature',
  190: 'Engine Speed',
  191: 'Transmission Output Shaft Speed',
  411: 'Engine EGR 1 Differential Pressure',
  412: 'Engine EGR 1 Temperature',
  441: 'Auxiliary Temperature 1',
  558: 'Accelerator Pedal 1 Low Idle Switch',
  597: 'Brake Switch',
  598: 'Clutch Switch',
  611: 'System Diagnostic Code 1 (Injector Wiring Shorted)',
  620: 'Sensor Supply Voltage 1 (+5V DC)',
  626: 'Engine Start Enable Device 1',
  627: 'Power Supply',
  629: 'Controller #1 (ECM)',
  630: 'Calibration Memory',
  633: 'Engine Fuel Actuator 1 Control Command',
  636: 'Engine Position Sensor',
  637: 'Engine Timing Sensor',
  639: 'SAE J1939 Network #1 (Primary Vehicle Network)',
  641: 'Engine Variable Geometry Turbocharger Actuator 1',
  651: 'Engine Injector Cylinder #01',
  652: 'Engine Injector Cylinder #02',
  653: 'Engine Injector Cylinder #03',
  654: 'Engine Injector Cylinder #04',
  655: 'Engine Injector Cylinder #05',
  656: 'Engine Injector Cylinder #06',
  677: 'Engine Starter Motor Relay',
  723: 'Engine Speed Sensor #2',
  729: 'Engine Inlet Air Heater Driver 1',
  1072: 'Engine Compression Brake Output 1',
  1076: 'Engine Fuel Injection Pump Fuel Control Valve',
  1172: 'Turbocharger 1 Compressor Inlet Temperature',
  1188: 'Turbocharger 1 Wastegate Actuator',
  1347: 'Engine Fuel Pump Pressurizing Assembly #1',
  1761: 'Aftertreatment 1 Diesel Exhaust Fluid Tank Level',
  2623: 'Accelerator Pedal Position 2',
  2791: 'Engine EGR 1 Valve Control',
  3216: 'Aftertreatment 1 Intake NOx',
  3226: 'Aftertreatment 1 Outlet NOx',
  3242: 'Aftertreatment 1 Diesel Particulate Filter Intake Gas Temperature',
  3246: 'Aftertreatment 1 Diesel Particulate Filter Outlet Gas Temperature',
  3251: 'Aftertreatment 1 Diesel Particulate Filter Differential Pressure',
  3361: 'Aftertreatment 1 Diesel Exhaust Fluid Dosing Unit',
  3363: 'Aftertreatment 1 Diesel Exhaust Fluid Tank Heater',
  3364: 'Aftertreatment 1 Diesel Exhaust Fluid Quality',
  3480: 'Aftertreatment 1 Fuel Pressure 1',
  3509: 'Sensor Supply Voltage 1',
  3510: 'Sensor Supply Voltage 2',
  3511: 'Sensor Supply Voltage 3',
  3556: 'Aftertreatment 1 Hydrocarbon Doser',
  3597: 'ECU Power Output Supply Voltage #1',
  3719: 'Aftertreatment 1 Diesel Particulate Filter Soot Load Percent',
  3720: 'Aftertreatment 1 Diesel Particulate Filter Ash Load Percent',
  4094: 'NOx Limits Exceeded (DEF Inducement)',
  4096: 'NOx Limits Exceeded - Severity',
  4334: 'Aftertreatment 1 Diesel Exhaust Fluid Doser Absolute Pressure',
  4364: 'Aftertreatment 1 SCR Conversion Efficiency',
  5571: 'High Pressure Common Rail Fuel Pressure Relief Valve',
}

export function spnName(spn: number): string {
  return SPN_NAMES[spn] ?? `Suspect Parameter Number ${spn}`
}
